theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
"device" = "wlp1s0"
ip = true
speed_up = true
graph_up = false
speed_down = true
graph_down = false
interval = 2

[[block]]
block = "disk_space"
path = "/"
alias = "HDD"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 5
show = "both"
device = "BAT1"

[[block]]
block = "time"
interval = 60
format = "%Y/%m/%d %a %R"
