theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "custom"
command = "who | grep 'pts/' | wc -l | tr '\\n' '/'; who | wc -l"
interval = 3

[[block]]
block = "toggle"
text = "SSHd"
command_state = "systemctl is-active sshd | grep '^a'"
command_on = "sudo systemctl start sshd"
command_off = "sudo systemctl stop sshd"
interval = 5

[[block]]
block = "net"
"device" = "wlp1s0"
ip = false
speed_up = true
graph_up = false
speed_down = true
graph_down = false
interval = 2

[[block]]
block = "disk_space"
path = "/"
alias = "HDD"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 2

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 5
show = "both"
device = "BAT1"

[[block]]
block = "time"
interval = 10
timezone = "Europe/Paris"
format = "[FR] %R"

[[block]]
block = "time"
interval = 10
timezone = "America/Sao_Paulo"
format = "[BR] %Y/%m/%d %a %R"
