theme = "solarized-dark"
icons = "awesome5"

[[block]]
block = "custom"
command = "echo -n ' '; who | grep 'pts/' | wc -l | tr '\\n' '/'; who | wc -l"
interval = 3

[[block]]
block = "toggle"
text = " "
command_state = "systemctl is-active -q sshd && echo a"
command_on = "sudo systemctl start sshd"
command_off = "sudo systemctl stop sshd"
interval = 5
[block.theme_overrides]
idle_bg = "#000000"

[[block]]
block = "toggle"
text = ""
command_state = "bluetoothctl show | grep 'Powered: yes'"
command_on = "sudo rfkill unblock bluetooth && sudo systemctl start bluetooth && bluetoothctl --timeout 4 power on"
command_off = "bluetoothctl --timeout 4 power off; sudo systemctl stop bluetooth && sudo rfkill block bluetooth"
interval = 5
[block.theme_overrides]
idle_bg = "#000000"

[[block]]
block = "toggle"
text = ""
command_state = "nmcli r wifi | grep '^d'"
command_on = "nmcli r wifi off"
command_off = "nmcli r wifi on"
interval = 5
[block.theme_overrides]
idle_bg = "#000000"

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} ({signal_strength}) {speed_down;K*b} {speed_up;K*b}"
hide_inactive = true
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "HD"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "{icon} {available}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
clickable = false

[[block]]
block = "cpu"
interval = 2

[[block]]
block = "temperature"
collapsed = false
format = "{average}"
chip = "k10temp-pci-00c3"
interval = 5

[[block]]
block = "temperature"
collapsed = false
format = "{average}"
chip = "amdgpu-pci-0900"
interval = 5

[[block]]
block = "sound"

[[block]]
block = "custom"
command = "(date +'%d/%m'; TZ='America/Sao_Paulo' date +'BR{%H:%M}'; TZ='Europe/Madrid' date +'ES{%H:%M}') | tr '\\n' ' '"
interval = 10
